apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  locations: koreacentral
  storageAccount: azure_storage_account_name

                                                                   